### ISSUE TITLE
Addon always reports pairing successful

### ISSUE THREAD

**Issue by leit512** [wackerl91/luna#51]
When I enter a wrong ip address, I don't get the enter-the-pin message and the dialog closes, but the addon still shows a successfully paired message.

**Comment by leit512** [comment]
This might or might not be the same issue:
With the 0.5.2 version I can't see the game list. The only entry is something like "enerating certificates.. done". So the problem might be that Luna does not connect to gamestream even with the correct ip address and pin.

This does not happen with the 0.5.1 version of the plugin.

I'm using osmc on the rpi2.

**Comment by wackerl91** [comment]
Thanks for the heads up! I'll have a look at this once I have access to my hardware again (probably next week). That being said, both versions should behave pretty much the same regarding pairing and the game list as the only difference between both versions is that 0.5.2 filters two additional outputs which were added in moonlight-embedded 2.1.3. The processes of pairing and getting the game list are otherwise identical in both versions.
"erating certificates.. done" should never be present unless you deleted the certificates and key files in moonlight's cache (and again, this would affect both versions). So if you haven't paired your host while using 0.5.2. and attempted to get a game list this line would be present. Reverting back to 0.5.1. and pairing with your host this time would prevent moonlight from outputting this line. If this is not true in your case please tell me so I can have a closer look at this. Additionally I'd advise you to stick with a version that's working for you until a new version is released.
Either way, I totally agree that this should be filtered (and possibly throw an error instead) to not confuse users. @djrockgt already mentioned this in a private message a few days back so this is already on my list, even though it's not public (even better it is now) - it's just that I more or less refuse to work on Luna if I can't test the code a couple of times (unless it's something really abstract where I can just run my tests) and since I don't have a spare Pi lying around this sometimes proves difficult. 
Again, thanks for the report. This kind of input is extremely valuable for me since I'm still working on Luna (mostly) alone and testing every single combination of edge cases just isn't possible in my spare time.

**Comment by sheldon** [comment]
hey there

i did a new install of both moonlight & luna today, from the latest versions for the first time. i bumped into the "erating certificates.. done" being the only game in my list. on advice in one of your other closed issues, i cleaned the game cache, and then next time i went to the game list it populated perfectly.

not sure if it's related to this bug, happy to open a new issue if you'd like, or even provide logs if it helps debug :+1: 

cheers and thanks for the awesome software!

**Comment by wackerl91** [comment]
Heya @sheldon,
what you're seeing is totally related to this bug. Need to do some more testing with the newest moonlight-embedded version to get it more stable again. They added some new outputs which aren't caught properly in Luna.
I'll have a look at this probably today, but I can't provide an ETA for an update yet (just got home from a 10 day trip, so I kinda got a huge backlog right now).
Thanks for your input! Cheers!

**Comment by wackerl91** [comment]
Both mentioned issues (due to them being closely related) should be resolved in [Luna 0.5.3] (https://github.com/wackerl91/luna/releases/tag/v0.5.3-alpha)

**Comment by sheldon** [comment]
epic, thanks for the quick response

![](http://27.media.tumblr.com/tumblr_lv3ouieRHX1r6aoq4o1_500.gif)

**Comment by wackerl91** [comment]
You're welcome - hope it's working properly now! If not just open another issue :)
P.S.: That gif is amazing xD
