### ISSUE TITLE
FR: Controller Mapping for Kodi menu navigation

### ISSUE THREAD

**Issue by cricket007** [wackerl91/luna#69]
First off, great add-on, minus an issue I left over at [moonlight-embedded][1] (probably not Luna related, so I put it there) 

Anyways, I was wondering if it would be possible to have a controller mapping for in-game play as well as outside of Luna as a general remote control for Kodi navigation. 

I can see how that might be outside the scope of this add-on itself, but perhaps I could be directed to a starting point or resource to look at for how to get multiple "profiles" for a controller to work. 

I've looked at [Kodi - Remotes][2] and the config for a [Xbox360 Keymap][3], and there is a [Keymap editor addon][4], but I can picture Luna's part like so:

  1. Launch Luna
  2. Have settings panel for Kodi keymap and moonlight keymap
  3. When moonlight is launched, the Kodi process is killed, therefore the Kodi keymap isn't needed and the moonlight mapping is loaded
  4. Exiting moonlight, Kodi is relaunched, and the mappings switch back. 

I know that RetroPie allows for multiple controllers to allow multiplayer games, but I only have one controller that I would like to use as both a Kodi remote and a game controller. 

**My Setup** 
Latest OSMC on Raspberry Pi 3
Bluetooth PS3 Controller (using QtSixA driver, I think)
Auto-updates on mostly everything

  [1]: https://github.com/irtimmer/moonlight-embedded/issues/372
  [2]: http://kodi.wiki/view/Category:Remotes
  [3]: http://kodi.wiki/view/Xbox_360_Wireless_Controller
  [4]: http://kodi.wiki/view/Add-on:Keymap_Editor

**Comment by wackerl91** [comment]
@cricket007 I got to say, this is one of the most beautifully formatted FRs ever - plus you really did your own research, appreciate that!

All I can say for now is that I'll have a look at this sooner or later - if you've followed Luna's development a bit closer you probably know that stuff like this gets me hooked up pretty fast, so if you're lucky it will be sooner ;) As usual, I can't give you an ETA on this, but I wouldn't expect anything more concrete too soon (got exams coming up).

To get a few things out of the way, though:
- the mapping file used for moonlight is passed via the configuration file (you should find it at `/home/osmc/.kodi/userdata/addon_data/script.luna/.storage`), so it's "auto-loaded" by moonlight
- I expect pretty much the same to happen for Kodi keymaps (i.e. Kodi is auto-loading its keymap XMLs once it starts)
- I will probably not be able to support input devices which aren't supported by Kodi, so I can't tell you if it would be possible to support your PS3 controller properly - at least not without doing further research. Luna has no control over Kodi and its input stream whatsoever, so I can't just hijack it (well, technically I could probably translate specific button presses to specific keys and send them to Kodi on a virtual keyboard, but that's the kind of stuff you really shouldn't do).

The two different mapping files shouldn't interfere by default, as neither of them can be loaded by the other application and neither of them is "global" (i.e. passed to the driver, which obviously keeps running).

I'll let you know once I know more about this topic. Meanwhile thanks for your request - I sincerely believe that this would be a great addition for many users!

**Comment by cricket007** [comment]
> this is one of the most beautifully formatted FRs ever

Thanks, I do a lot of note-taking in Markdown. :smiley: 

> got exams coming up

Understandable, I'm willing to look into it more myself, I just wanted to document my thoughts about the feature somewhere. I might hit RetroPie's Github/forum at some point as well. 

> technically I could probably translate specific button presses to specific keys and send them to Kodi on a virtual keyboard... The two different mapping files shouldn't interfere by default, as neither of them can be loaded by the other application and neither of them is "global"

Regarding the virtual keyboard, I can't remember exactly which set of instructions that finally got my PS3 controller working over bluetooth, but somewhere along that process, I did have the controller working as a Kodi remote. I could use the D-pad for menus, start/stop/skip music, change the volume, etc. all from the controller. I'll need to poke around my filesystem to see if I still have that file somewhere. 

In any case, I believe I tested that setup with moonlight before I found Luna and it seemed that the  "virtual keyboard" mapping was configured globally at the operating system level, and so all the controller buttons were being detected as keyboard input, which was not ideal for the games I was testing.

**Comment by wackerl91** [comment]
> Regarding the virtual keyboard, I can't remember exactly which set of instructions that finally got my PS3 controller working over bluetooth, but somewhere along that process, I did have the controller working as a Kodi remote. I could use the D-pad for menus, start/stop/skip music, change the volume, etc. all from the controller. [...] it seemed that the "virtual keyboard" mapping was configured globally at the operating system level, and so all the controller buttons were being detected as keyboard input, which was not ideal for the games I was testing.

I obviously wasn't clear with my answer above regarding this part, I'm sorry. Both xboxdrv and QtSixA have the option to load driver level configuration files, which will "conflict" with other configurations / mappings for specific programs. What I mean by this is (and I know that this is totally not a real world example, just want to make a point here) that if button X on your PS3 controller is mapped to a [Enter] key press, there's nothing moonlight can do about that - it's most likely passed as an [Enter] key code and interpreted as such. This is probably the issue you were seeing before and and what I meant by
> neither of them [moonlight's or kodi's button map] is "global" (i.e. passed to the driver, which obviously keeps running).

So a configuration file passed to the driver will stay the same as long as it's running. At least for xboxdrv (not too familiar with QtSixA; tried to use it, bought a wireless X360 kit after two days) has no option to reload its config file, so the only way I can see this working is shutting down the driver and starting it again (using a different config file of course). This approach will only work if the driver isn't running as root, which probably isn't the case for most people - even the xboxdrv documentation "recommends" starting the driver as root to not have to worry about access permissions on /dev/input/uinput - and since all of this (OSMC, moonlight and Luna) is supposed to make using a mediacenter and streaming games as easy as possible, I can't see many people actually properly configuring their system to start the driver as the current user - adding it to rc.local is just so much more painless. In short: reloading the driver to change it's configuration file won't be possible on most installations, so using a driver level configuration would be a big 'no no' for me.

From what I've just read around the web Kodi should support nearly every controller type out of the box - it's just missing the appropriate option on my installation, even though the default mapping files for Kodi itself are still around (they're all inside `/usr/share/kodi/system/keymaps`). My guess is that this feature has been removed from OSMC build for some reason, even requiring an ugly workaround for the X360 controllers (loading a specific map as driver configuration). I've also stumbled upon [this wiki entry](http://kodi.wiki/view/HOW-TO:Configure_controllers) which outlines the upcoming configuration process for v17. If this is coming to OSMC as well, it would make the feature in Luna obsolete so I'd probably keep waiting until the final version arrives on OSMC and see if this functionality is included before creating either an isolated approach or a(nother) workaround.
That being said, I'm still totally in favour of the general idea, just need to find an appropriate way to do this and I don't want to spend too much of my time crafting something that might become obsolete within months. Meanwhile I think we should keep the discussion going and I'm eager to see what you and others dig up. Maybe someone with a deeper understanding of how controller input is handled by OSMC drops in and shares his wisdom with us :)

P.S.: You may also want to try out the [OSMC test builds](https://discourse.osmc.tv/t/testing-kodi-17-krypton-builds-for-raspberry-pi-continued/14628) which are already using Kodi v17.

**Comment by cricket007** [comment]
Huh, good find on that v17 keymap entry. That did give me an idea that maybe I just need to make a keymap for my controller, and all will be good because I can get to the Luna addon, then Kodi is killed and the keymap is no longer in-use until restarted. 

> I did have the controller working as a Kodi remote. I could use the D-pad for menus, start/stop/skip music, change the volume, etc. all from the controller. I'll need to poke around my filesystem to see if I have that file somewhere

I found it. And it was a sixad configuration that remapped to keyboard input (as kindly label in the comments by someone online). As I said, worked alright, but not ideal for gaming.  

```ini
# ##########################
# sixad configuration file #
########################## #

# Features
enable_leds 1
enable_joystick 0
enable_input 1
enable_rumble 0
enable_timeout 1

# LED
led_n_auto 1
led_n_number 1
led_anim 1

# Joystick
enable_buttons 1
enable_sbuttons 1
enable_axis 1
enable_accel 1
enable_accon 0
enable_speed 0
enable_pos 0

# Input - "(None)"
key_select 31 # s: shutdown menu
key_start 164 # playpause

key_up 103 #up
key_right 106 #right
key_down 108 #down
key_left 105 #left

key_l1 104 # PAGEUP
key_r1 109 # PAGEDOWN
key_l2 17 # w/z: aspect ratio
key_r2 24 # o: codec info
key_l3 39 # semicolon/m: player control
key_r3 113 # mute

key_tri 46 # C: context menu
key_cir 14 # BACKSPACE
key_cro 28 # ENTER
key_squ 23 # info
#key_squ 57 # SPACE

key_ps 15 # tab: fullscreen

axis_left_type 2
axis_left_up 107 # end: end page
axis_left_right 39 # semicolon/dot: next
axis_left_down 102 # home: first page or home window
axis_left_left 50 # m/comma: previous
axis_right_type 2
axis_right_up 74 # volumeup
axis_right_right 33 # f: fast forward
axis_right_down 78 # volumedown
axis_right_left 19 # r: rewind
axis_speed 6
use_lr3 0

# Rumble
old_rumble_mode 0

# Timeout
timeout_mins 10
```

As a reference, here is current sixad profile at `/var/lib/sixad/profiles/default`

```ini
enable_leds 1
enable_joystick 1
enable_input 0 
enable_remote 0
enable_rumble 1
enable_timeout 1
led_n_auto 1
led_n_number 1
led_anim 1
enable_buttons 1
enable_sbuttons 1
enable_axis 1
enable_accel 0
enable_accon 0
enable_speed 0
enable_pos 0

# Rumble
old_rumble_mode 0

# Timeout
timeout_mins 10
```

**Comment by cricket007** [comment]
Well, I think I finally found my answer after quite a while of searching and no progress with different keymap configurations over the weekend. :cry: 

[osmc : Enable joystick support][1] is an open issue

  [1]: https://github.com/osmc/osmc/issues/162

**Comment by cricket007** [comment]
Turns out all I needed to do was enable joystick input with a change to this line

    enable_joystick 1

And then I magically have available inputs of

    event1 event2 js0 kbd mouse0

Compared to before of just 

    event js0

Moonlight works with the events on `event1` perfectly well and doesn't seem to interfere with the other inputs.

**Comment by wackerl91** [comment]
> Turns out all I needed to do was enable joystick input with a change to this line

May I ask in which file? Just for future reference (and for others who stumble upon this conversation).

> Moonlight works with the events on event1 perfectly well and doesn't seem to interfere with the other inputs.

Not too surprised about this because this is the behaviour I would expect. Only thing I wonder is why we don't have the option the enable gamepads in the settings on the Pi, but enabling it manually seems to work perfectly fine for you.
Either way, good find and thanks for letting me know!

**Comment by cricket007** [comment]
Edited above comment, but I'm working on a [Gist](https://gist.github.com/cricket007/a30e7233ada8bc6e336ae8b847d33f61) for writing down my complete notes if I ever flash a new SD card on my Pi

**Comment by wackerl91** [comment]
Ah, didn't see your edit, I'm sorry. Do you mind if I link to your gist from Luna's wiki? Pretty sure it might be helpful to others.

**Comment by cricket007** [comment]
Sure - I'd link myself, but haven't made an account. As I linked to earlier, the config actually initially came from [this post](https://discourse.osmc.tv/t/osmc-and-ps3-controller-how-to-install/9937/6)

> Only thing I wonder is why we don't have the option the enable gamepads in the settings

It was the keyboard input mapping that allowed Kodi navigation. Enabling the joystick was purely to get Moonlight working without interfering with the `event2` device which is what is inputting the keycodes to Kodi.
