### ISSUE TITLE
In Luna Steam is lagging, but not in moonlight itself

### ISSUE THREAD

**Issue by sapkra** [wackerl91/luna#79]
When I start Steam via Luna, the stream lags while navigating in the game overview. But I tested it with SSH: moonlight itself works fine.

**Comment by wackerl91** [comment]
This is most likely due to different configurations. Try loading the same config file Luna passes to moonlight and see if it behaves the same (i.e. lagging):
`moonlight -config /home/osmc/.kodi/userdata/addon_data/script.luna/.storage/luna.conf`
(depending on your OS and configuration the actual path may vary)

So far I've never encountered a case where starting moonlight directly versus starting it via Luna resulted in different performance when using the __same__ configuration.

**Comment by wackerl91** [comment]
Closed because:
* I can't reproduce this
* there was no more information posted regarding this issue after a month

If someone stumbles upon this in the future, feel free to reopen this issue but make sure to provide some additional information. Thanks!
